#!/bin/bash

dir=$(dirname "$0")
source $dir/funcs
PATH=$(readlink -f $dir):$PATH

(
echo
)&>/dev/null

set -e

doit --ignorerc cd $dir/../myapp
cd $dir/../myapp
rm -f myapp
doit cat Makefile

doit --ignorerc make

rm -f myapp
doit make -f .Makefile

background sudo ./myapp

sleep 1
echo

doit curl -s localhost:80
doit --ignorerc curl -s localhost:80/stop

doit ls -l
rm -f myapp
doit make -f .Makefile1
doit ls -l

doit --ignorerc which git
# doit alias git
