#!/bin/bash

set -ex

# Get/refresh some images we'll use during the Dojo
###################################################
docker pull ubuntu:14.04
docker pull tomcat
docker pull nginx
docker pull golang
docker pull ibmdojo/looper
docker pull ibmdojo/tiny
docker pull ibmdojo/httpd
docker pull ibmdojo/dind
docker pull dockercloud/haproxy
docker pull python:3-alpine
docker pull redis:3-alpine



docker tag ubuntu:14.04 ubuntu
docker tag nginx unknown

# curl -sS https://storage.googleapis.com/kubernetes-release/release/stable.txt
export K8S_VERSION=v1.3.4
docker pull gcr.io/google_containers/hyperkube-amd64:${K8S_VERSION}

# Clone (or update) some repos we'll need
#########################################
pushd $HOME

for repo in scripts goapp webapp; do
    if [ ! -d $repo ]; then
	    git clone https://github.com/ibm-dojo/$repo.git
    else
	    cd $repo
	    git pull
	    cd ..
    fi
done

rm -rf $HOME/layers
cp -r $HOME/scripts/layers $HOME/

popd

# Make sure our env is updated
##############################
if ! grep 'set -o vi' ~/.bashrc > /dev/null ; then
	echo 'set -o vi' >> .bashrc
fi

if ! grep '$HOME/scripts' ~/.bashrc > /dev/null ; then
        echo 'PATH=$PATH:$HOME/scripts' >> .bashrc
fi

rm -rf $HOME/tmp
mkdir $HOME/tmp
