#!/bin/bash

set -ex

docker pull ubuntu:14.04
docker tag ubuntu:14.04 ubuntu
docker pull tomcat
docker pull nginx
docker pull golang
docker pull ibmdojo/looper
docker pull ibmdojo/tiny
docker pull ibmdojo/httpd
docker pull ibmdojo/dind

export K8S_VERSION=$(curl -sS https://storage.googleapis.com/kubernetes-release/release/stable.txt)

docker pull gcr.io/google_containers/hyperkube-amd64:${K8S_VERSION}

pushd $HOME

for repo in scripts goapp webapps; do
    if [ ! -d $repo ]; then
	    git clone https://github.com/ibm-dojo/repo.git
    else
	    cd $repo
	    git pull
	    cd ..
    fi
done

popd
