#!/bin/bash

set -e

export DASHBOARD_URL=$HOME/user/scripts/kubernetes-dashboard.yaml
if kubedind up > ~/scripts/kubeStart.log 2>&1 ; then
	echo Kubernetes is ready
else
	cat ~/scripts/kubeStart.log
	echo "Somethient went wrong"
	exit 1
fi
