#!/bin/bash

(docker ps -a | grep gcr | while read id r;do docker rm -f $id; done) &> /dev/null
(docker ps -a | grep gcr | while read id r;do docker rm -f $id; done) &> /dev/null
(docker ps -a | grep gcr | while read id r;do docker rm -f $id; done) &> /dev/null

echo Kubernetes should be stopped now
