#!/bin/bash

dir=$(dirname "$0")
source $dir/demoscript
PATH=$(readlink -f $dir):$PATH

(
docker rm -f myapp test
docker rm -f test myapp
docker network rm net1
)&>/dev/null

set -e

doit docker network create net1
doit docker run -dti --net net1 --name myapp docker:5000/myapp:1.0
doit docker run -dti --name test alpine sh
doit --ignorerc docker exec test ping -c 1 myapp
doit docker network connect net1 test
doit docker exec test ping -c 1 myapp

doit docker rm -f test myapp
doit docker network rm net1
