#!/bin/bash

source funcs

(kubectl delete -f pod.yaml ; kubectl delete pod httpd-pod) &> /dev/null
wait ! kubectl get pod httpd-pod

set -e

doit cat pod.yaml
doit kubectl create -f pod.yaml
doit kubectl get pods

comment Waiting for it to start...
wait kubectl get pod httpd-pod \| grep "1/1"

doit kubectl describe pod/httpd-pod
IP=$(grep "IP:" out | sed "s/.*IP: *//")

doit curl $IP

doit kubectl delete -f pod.yaml
wait ! kubectl get pod httpd-pod

doit kubectl get pods
