#!/bin/bash

source funcs
dir=$(dirname "$0")

(docker rm -f `docker ps -aq` >& /dev/null )

set -e

doit docker version

doit docker run ubuntu echo Hello World

doit docker run ubuntu ps -ef
ttyRun docker run -ti ubuntu bash 10<<EOF
  pwd
EOF

doit docker run -d --name zzz ubuntu sleep 6000

doit docker inspect zzz
doit docker inspect --format "{{.NetworkSettings.IPAddress}}" zzz

doit docker exec zzz ps -ef

ttyRun docker exec -ti zzz bash 10<<EOF
  pwd
  ps -ef
  ls
EOF

doit docker top zzz
doit ps -ef \| grep sleep

doit docker run -d unknown
ID=$(cat out)
doit docker top $ID
doit docker exec $ID ps -ef
doit docker exec $ID cat /etc/os-release
doit docker inspect --format "{{.NetworkSettings.IPAddress}}" $ID
IP=$(cat out)
doit curl $IP

doit docker ps

doit docker stop zzz
doit docker stop $ID

doit docker ps
doit docker start zzz
doit docker ps

doit docker restart zzz
doit docker stop zzz

doit docker ps
doit docker ps -a

doit docker rm zzz $ID
doit docker ps -a

doit docker run -d ubuntu sleep 6000
ID=$(cat out)
doit ! docker rm $ID
doit docker rm -f $ID

doit docker rm -f $(docker ps -aq)

doit docker run -tid ibmdojo/looper
ID=$(cat out)
ttyRun  docker attach --detach-keys ctrl-p $ID 10<<EOF
run sleep 3

EOF
doit docker ps
ttyRun docker attach --detach-keys a $ID 10<<EOF
run sleep 3
a
EOF

doit docker run --help

doit docker run --rm ubuntu sleep 5
sleep 6
doit docker ps -a
doit docker run -e myEnv=myValue ubuntu env
doit docker run -w /usr ubuntu bash -c 'pwd && ls -C'

doit docker run -d ibmdojo/looper
ID=$(cat out)
sleep 3
doit docker logs $ID

ttyRun ! docker stats 10<<EOF
run sleep 5 

EOF
doit docker rm -f $ID

doit docker run --name scary ubuntu rm /etc/passwd
doit docker diff scary
doit docker rm scary

doit docker run -d ibmdojo/tiny
ID=$(cat out)
doit docker cp $ID:/hello .
doit ls -l hello
doit docker rm -f $ID

doit date \> foo
doit docker run -tid --name test ubuntu bash
doit docker cp foo test:/tmp/
doit docker exec test ls -l /tmp
ttyRun docker attach test 10<<EOF

ls -l /tmp
EOF
doit docker rm -f test
doit rm foo

doit docker run -d --name loop ibmdojo/looper
doit docker kill loop
doit docker rm -f loop

background docker run --name loop ibmdojo/looper
sleep 2
doit docker pause loop
sleep 2
doit docker unpause loop
sleep 2
doit docker rm -f loop

doit docker run -d --name zzz ubuntu sleep 3
doit docker wait zzz
doit docker rm zzz

doit docker events --since 5m --until 0s

doit docker info

doit docker run -dP nginx
ID=$(cat out)
doit docker ps
port=$(grep tcp out | sed "s/.*:\([^-]*\)-.80.*/\1/")
doit curl http://localhost:$port

doit docker run -d -p 8080:80 ubuntu sleep 600
ID=$(cat out)
ID=${ID:0:3}
doit docker port $ID
doit docker port $ID 80
doit ! docker port $ID 81

echo All done

rm -f cmds out hello
