#!/bin/bash

dir=$(dirname "$0")
source $dir/demoscript
PATH=$(readlink -f $dir):$PATH

(
docker service rm $(docker service ls -q)
docker exec -ti node1 docker swarm leave
docker exec -ti node2 docker swarm leave
docker exec -ti node3 docker swarm leave
docker swarm leave --force
docker rm -f node1 node2 node3
docker rm -f $(docker ps -aq)
)&>/dev/null

set -e

comment Running swarmDemo1
swarmDemo1

comment Running swarmDemo2
swarmDemo2

pushd $(readlink -f $dir/../myapp) > /dev/null
doit docker build -f Dockerfile3 -t docker:5000/myapp:2.0 .
doit docker push docker:5000/myapp:2.0
popd > /dev/null

comment Running swarmDemo3
swarmDemo3

comment Running swarmDemo9
swarmDemo9
