#!/bin/bash

dir=$(dirname "$0")
source $dir/demoscript
PATH=$(readlink -f $dir):$PATH

node3IP=$(docker inspect --format "{{.NetworkSettings.Networks.bridge.IPAddress}}" node3)

set -e

comment Upgrade the service from 1.0 to 2.0
comment In another window run: docker exec -ti node3 watch -d -n 1 curl -s 127.0.0.1
doit docker service update --image=docker:5000/myapp:2.0 myapp
