#!/bin/bash

dir=$(dirname "$0")
source $dir/funcs
PATH=$(readlink -f $dir):$PATH

set -e

doit --ignorerc docker service rm myapp
doit --ignorerc docker rm -f node1 node2 node3
doit --ignorerc docker swarm leave --force
rm -f node3.cmd
