#!/bin/bash

dir=$(dirname "$0")
source $dir/demoscript
PATH=$(readlink -f $dir):$PATH

set -e

doit --ignorerc docker service rm myapp
doit --ignorerc docker exec -ti node1 docker swarm leave --force
doit --ignorerc docker exec -ti node2 docker swarm leave --force
doit --ignorerc docker exec -ti node3 docker swarm leave --force
doit --ignorerc docker rm -f node1 node2 node3
doit --ignorerc docker swarm leave --force
rm -f node3.cmd
doit --ignorerc docker rm -f registry
