#!/bin/bash

source funcs
dir=$(dirname "$0")

node3IP=$(docker inspect --format "{{.NetworkSettings.Networks.bridge.IPAddress}}" node3)

set -e

comment Upgrade the service from 1.0 to 2.0
comment In another window run: watch -d -n 0.5 curl --silent $node3IP
doit docker service update --image=docker:5000/myapp:2.0 myapp
