#!/bin/bash
(docker service rm $(docker service ls -q);docker exec -ti node1 docker swarm leave;docker exec -ti node2 docker swarm leave;docker swarm leave --force;docker rm -f node1 node2)&>/dev/null

bold=$(tput bold)
normal=$(tput sgr0)

function doit() {
	set +e
	echo -n $bold"$"$normal" "
	if [[ "$SKIP" == "" ]]; then read -s -n 1 ; fi
	echo -n $bold$*$normal" "
	echo "$*" >> cmds
	if [[ "$SKIP" == "" ]]; then read -s -n 1 ; fi
	echo
	$* 2>err >out
	rc=$?
	cat err out
	[[ "$rc" == "0" ]] || exit
	echo
	set -e
}

set -e

doit docker swarm init --secret please
joinIP=$(grep 2377 out)

doit docker run --privileged -dti --name node1 --hostname node1 ibmdojo/dind
doit docker inspect --format "{{.NetworkSettings.Networks.bridge.IPAddress}}" node1
node1IP=$(docker inspect --format "{{.NetworkSettings.Networks.bridge.IPAddress}}" node1)
doit docker run --privileged -dti --name node2 --hostname node2 ibmdojo/dind
doit docker inspect --format "{{.NetworkSettings.Networks.bridge.IPAddress}}" node2
node2IP=$(docker inspect --format "{{.NetworkSettings.Networks.bridge.IPAddress}}" node2)

doit docker exec -ti node1 docker swarm join --secret please $joinIP
doit docker exec -ti node2 docker swarm join --secret please $joinIP

doit docker service create --name mini -p 80:80 ibmdojo/mini

doit docker service ls
echo -e $bold"Waiting for it to start...\\n"$normal
while !(docker service ls|grep "1/1"&>/dev/null);do sleep 1;done

doit curl --silent 127.0.0.1

doit docker service scale mini=3
echo -e $bold"Waiting for it to scale...\\n"$normal
while !(docker service ls|grep "3/3");do sleep 1;done
doit docker service ls

doit curl --silent $node1IP
doit curl --silent $node2IP

doit docker service rm mini
doit docker rm -f node1 node2
doit docker swarm leave --force
rm -f out err cmds
