#!/bin/bash

source ../funcs

doit docker-compose up -d

echo "In another terminal, run 'watch -n1 -d curl 0.0.0.0'"

doit docker-compose scale web=3

sleep 5

echo "The current directory is mounted and automatically refreshed by flask. Edit 'app.py' for live reloads"

doit docker-compose down

